import { Router } from 'express';
import authRoutes from './auth';
import candidateRoutes from './candidates';
import documentRoutes from './documents';
import timelineRoutes from './timeline';
import employerRoutes from './employers';
import jobOrderRoutes from './jobOrders';
import cvGeneratorRoutes from './cvGenerator';
import matchingRoutes from './matching';
import communicationRoutes from './communication';
import searchRoutes from './search';
import inboxRoutes from './inbox';
import whatsappRoutes from './whatsapp';
import whatsappBridgeRoutes from './whatsappBridge';
import whatsappInboxRoutes from './whatsappInbox';
import gmailRoutes from './gmail';
import testHelperRoutes from './testHelpers';
import parsingJobsRoutes from './parsingJobs';
import queueHealthRoutes from './queueHealth';
import storageHealthRoutes from './storageHealth';
import verificationLogsRoutes from './verificationLogs';
import extractPhotoRoutes from './extractPhoto';
import employeeLogsRoutes from './employeeLogs';
import { emailRouter } from './emailRoutes';
import gmailAdminRoutes from './gmailAdmin';
import reviewRoutes from './reviewRoutes';
import onboardingRoutes from './onboarding';
import { getWorkerStatus } from '../controllers/workerStatusController';

const router = Router();

router.use('/auth', authRoutes);
router.use('/candidates', candidateRoutes);
router.use('/candidates', extractPhotoRoutes);
router.use('/documents', documentRoutes);
router.use('/timeline', timelineRoutes);
router.use('/employers', employerRoutes);
router.use('/job-orders', jobOrderRoutes);
router.use('/cv-generator', cvGeneratorRoutes);
router.use('/matching', matchingRoutes);
router.use('/communication', communicationRoutes);
router.use('/search', searchRoutes);
router.use('/cv-inbox', inboxRoutes);
router.use('/whatsapp-inbox', whatsappInboxRoutes);
router.use('/whatsapp-bridge', whatsappBridgeRoutes);
router.use('/webhooks/whatsapp', whatsappRoutes);
router.use('/webhooks/gmail', gmailRoutes);
router.use('/test', testHelperRoutes);
router.use('/parsing-jobs', parsingJobsRoutes);
router.use('/health', queueHealthRoutes);
router.use('/health/storage', storageHealthRoutes);
router.use('/verification-logs', verificationLogsRoutes);
router.use('/employee-logs', employeeLogsRoutes);
router.use('/email', emailRouter);
router.use('/gmail-admin', gmailAdminRoutes);
router.use('/review', reviewRoutes);
router.use('/onboarding', onboardingRoutes);
router.get('/worker-status', getWorkerStatus);

export default router;
