param(
  [Parameter(Mandatory=$true)] [string]$ApiBaseUrl,
  [Parameter(Mandatory=$true)] [string]$FilePath,
  [string]$Source = 'api',
  [string]$ExternalMessageId,
  [string]$Status = 'pending'
)

<#
.SYNOPSIS
Uploads a CV PDF as an inbox message + attachment, then triggers parsing.

.PARAMETER ApiBaseUrl
Backend base URL including /api, e.g. https://your-backend.railway.app/api

.PARAMETER FilePath
Absolute path to the CV file to upload.

.PARAMETER Source
Source tag for the message (default: api)

.PARAMETER ExternalMessageId
Optional unique external message id; autogenerated if omitted.

.PARAMETER Status
Initial message status (default: pending)

.EXAMPLE
./upload-cv.ps1 -ApiBaseUrl https://backend.up.railway.app/api -FilePath "D:\CVs\Candidate.pdf"
#>

function New-ExternalMessageId {
  param([string]$FilePath)
  $base = [System.IO.Path]::GetFileNameWithoutExtension($FilePath)
  $ts = [DateTime]::UtcNow.ToString('yyyyMMddHHmmssffff')
  return "manual_${base}_${ts}"
}

function Invoke-ApiRequest {
  param(
    [string]$Method,
    [string]$Path,
    [object]$Body
  )
  $uri = "$ApiBaseUrl$Path"
  $json = $null
  if ($Body -ne $null) { $json = ($Body | ConvertTo-Json -Depth 6) }
  Write-Host "-> $Method $uri" -ForegroundColor Cyan
  $res = Invoke-WebRequest -UseBasicParsing -Method $Method -Uri $uri -ContentType 'application/json' -Body $json -ErrorAction Stop
  $text = $res.Content
  try { return @{ status = $res.StatusCode; json = ($text | ConvertFrom-Json) } } catch { return @{ status = $res.StatusCode; json = $text } }
}

if (-not (Test-Path -LiteralPath $FilePath)) {
  Write-Error "File not found: $FilePath"
  exit 1
}

$name = [System.IO.Path]::GetFileName($FilePath)
$ext = [System.IO.Path]::GetExtension($FilePath).ToLowerInvariant()
switch ($ext) {
  '.pdf' { $mime = 'application/pdf' }
  '.doc' { $mime = 'application/msword' }
  '.docx' { $mime = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' }
  default { $mime = 'application/octet-stream' }
}

if (-not $ExternalMessageId -or $ExternalMessageId.Trim().Length -eq 0) {
  $ExternalMessageId = New-ExternalMessageId -FilePath $FilePath
}

Write-Host "Creating inbox message: source=$Source external_message_id=$ExternalMessageId" -ForegroundColor Green
$createRes = Invoke-ApiRequest -Method 'POST' -Path '/cv-inbox' -Body @{ 
  source = $Source; 
  external_message_id = $ExternalMessageId; 
  payload = @{ text = "Manual upload: $name" }; 
  status = $Status; 
  received_at = ([DateTime]::UtcNow.ToString('o')) 
}
if ($createRes.status -ge 300) { Write-Error "Create message failed: $($createRes.status) $($createRes.json)"; exit 1 }
$messageId = $createRes.json.id
Write-Host "Message created: $messageId" -ForegroundColor Green

Write-Host "Reading and encoding file: $name ($mime)" -ForegroundColor Green
$bytes = [IO.File]::ReadAllBytes($FilePath)
$b64 = [Convert]::ToBase64String($bytes)

Write-Host "Uploading attachment..." -ForegroundColor Green
$attachRes = Invoke-ApiRequest -Method 'POST' -Path "/cv-inbox/$messageId/attachments" -Body @{ 
  file_base64 = $b64; 
  file_name = $name; 
  mime_type = $mime; 
  attachment_type = 'cv';
  storage_bucket = 'documents';
  storage_path = "inbox/$messageId/$name" 
}
if ($attachRes.status -ge 300) { Write-Error "Upload attachment failed: $($attachRes.status) $($attachRes.json)"; exit 1 }
$attachmentId = $attachRes.json.id
Write-Host "Attachment uploaded: $attachmentId" -ForegroundColor Green

Write-Host "Triggering parsing..." -ForegroundColor Green
$processRes = Invoke-ApiRequest -Method 'POST' -Path "/cv-inbox/attachments/$attachmentId/process" -Body @{}
if ($processRes.status -ge 300) {
  Write-Warning "Trigger parsing returned non-2xx: $($processRes.status) $($processRes.json)"
} else {
  Write-Host "Parsing queued: job_id=$($processRes.json.job_id) status=$($processRes.json.status)" -ForegroundColor Green
}

Write-Host "Done." -ForegroundColor Green
