export interface Candidate {
  id: string;
  name: string;
  email: string;
  phone: string;
  nationality: string;
  position: string;
  country: string; // Country of interest (where they want to work)
  experience: number;
  status: 'Applied' | 'Pending' | 'Cancelled' | 'Deployed';
  source: 'WhatsApp' | 'Email' | 'Form' | 'Manual';
  passportAvailable: boolean;
  skills: string[];
  appliedDate: string;
  videoLink?: string;
  cvUrl?: string;
  notes?: string;
  languages?: string[];
  aiScore?: number;
  // AI Extraction fields
  autoExtracted?: boolean;
  extractionConfidence?: number;
  needsReview?: boolean;
  reviewedBy?: string;
  reviewedDate?: string;
  // Shareable links
  profileLink?: string; // Unique profile link
  cvShareLink?: string; // Recruiter CV share link
  // Additional Excel fields
  age?: number;
  dateOfBirth?: string;
  passportNumber?: string;
  passportExpiry?: string;
  medicalExpiry?: string;
  religion?: string;
  maritalStatus?: 'Single' | 'Married' | 'Divorced' | 'Widowed';
  currentLocation?: string;
  salaryExpectation?: string;
  availableFrom?: string;
  lastContacted?: string;
  interviewDate?: string;
  interviewStatus?: string;
  linkedinUrl?: string;
  whatsappLink?: string;
  drivingLicense?: string;
  yearsInGCC?: number;
  englishLevel?: 'Basic' | 'Intermediate' | 'Fluent' | 'Native';
  arabicLevel?: 'None' | 'Basic' | 'Intermediate' | 'Fluent';
}

export interface Employer {
  id: string;
  companyName: string;
  country: string;
  contactPerson: string;
  email: string;
  phone: string;
  categories: string[];
  activeJobs: number;
}

export interface JobOrder {
  id: string;
  employerId: string;
  employerName: string;
  position: string;
  country: string;
  salary: string;
  candidates: number;
  urgency: 'Low' | 'Medium' | 'High';
  skills: string[];
  status: 'Open' | 'Closed';
  createdDate: string;
}

export const mockCandidates: Candidate[] = [
  // Auto-extracted candidates (needs review)
  {
    id: 'AUTO-001',
    name: 'Maria Garcia',
    email: 'maria.garcia@email.com',
    phone: '+63 917 123 4567',
    nationality: 'Philippines',
    position: 'Housemaid',
    country: 'Saudi Arabia',
    experience: 3,
    status: 'Applied',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Cleaning', 'Cooking', 'Child Care', 'Laundry'],
    appliedDate: '2025-12-13',
    languages: ['English', 'Tagalog', 'Arabic (Basic)'],
    aiScore: 7.2,
    autoExtracted: true,
    extractionConfidence: 88,
    needsReview: false,
    cvUrl: 'Maria_Garcia_CV.pdf'
  },
  {
    id: 'AUTO-002',
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '+92 301 987 6543',
    nationality: 'Pakistan',
    position: 'Construction Worker',
    country: 'UAE',
    experience: 6,
    status: 'Applied',
    source: 'Email',
    passportAvailable: true,
    skills: ['Masonry', 'Carpentry', 'Concrete Work', 'Safety'],
    appliedDate: '2025-12-13',
    languages: ['English', 'Urdu'],
    aiScore: 8.0,
    autoExtracted: true,
    extractionConfidence: 72,
    needsReview: true,
    cvUrl: 'John_Smith_CV.docx'
  },
  {
    id: 'AUTO-003',
    name: 'Mohammed Aslam',
    email: '', // Missing - needs review
    phone: '+92 302 555 1234',
    nationality: 'Pakistan',
    position: 'Driver',
    country: 'Saudi Arabia',
    experience: 4,
    status: 'Applied',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Light Vehicle', 'Heavy Vehicle', 'Clean License'],
    appliedDate: '2025-12-12',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 7.8,
    autoExtracted: true,
    extractionConfidence: 68,
    needsReview: true,
    cvUrl: 'Mohammed_Aslam_CV.pdf'
  },
  // Regular candidates
  {
    id: '1',
    name: 'Ahmed Hassan',
    email: 'ahmed.hassan@email.com',
    phone: '+92 300 1234567',
    nationality: 'Pakistan',
    position: 'Electrician',
    country: 'UAE',
    experience: 5,
    status: 'Pending',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Electrical Installation', 'Maintenance', 'Industrial Wiring', 'Safety Standards'],
    appliedDate: '2025-12-10',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.5,
    age: 32,
    dateOfBirth: '1993-05-15',
    passportNumber: 'AB1234567',
    passportExpiry: '2028-03-20',
    medicalExpiry: '2026-01-15',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Lahore, Pakistan',
    salaryExpectation: 'AED 2,000',
    availableFrom: '2026-01-01',
    lastContacted: '2025-12-15',
    interviewDate: '2025-12-22',
    interviewStatus: 'Scheduled',
    linkedinUrl: 'https://linkedin.com/in/ahmed-hassan-electrician',
    whatsappLink: 'https://wa.me/923001234567',
    videoLink: 'https://youtube.com/watch?v=abc123xyz',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 2,
    englishLevel: 'Intermediate',
    arabicLevel: 'Basic',
  },
  {
    id: '2',
    name: 'Mohammed Ali',
    email: 'mohammed.ali@email.com',
    phone: '+92 301 2345678',
    nationality: 'Pakistan',
    position: 'Welder',
    country: 'Saudi Arabia',
    experience: 7,
    status: 'Deployed',
    source: 'Form',
    passportAvailable: true,
    skills: ['TIG Welding', 'MIG Welding', 'Arc Welding', 'Metal Fabrication'],
    appliedDate: '2025-11-15',
    languages: ['English', 'Urdu'],
    aiScore: 9.2,
    age: 35,
    dateOfBirth: '1990-08-22',
    passportNumber: 'CD9876543',
    passportExpiry: '2029-06-10',
    medicalExpiry: '2026-11-20',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Riyadh, Saudi Arabia',
    salaryExpectation: 'SAR 2,500',
    availableFrom: 'Currently Working',
    lastContacted: '2025-12-01',
    linkedinUrl: 'https://linkedin.com/in/mohammed-ali-welder',
    whatsappLink: 'https://wa.me/923012345678',
    videoLink: 'https://youtube.com/watch?v=def456uvw',
    drivingLicense: 'None',
    yearsInGCC: 5,
    englishLevel: 'Basic',
    arabicLevel: 'Intermediate',
  },
  {
    id: '3',
    name: 'Rajesh Kumar',
    email: 'rajesh.kumar@email.com',
    phone: '+91 98765 43210',
    nationality: 'India',
    position: 'Mason',
    country: 'Qatar',
    experience: 4,
    status: 'Applied',
    source: 'Email',
    passportAvailable: true,
    skills: ['Bricklaying', 'Plastering', 'Tiling', 'Construction'],
    appliedDate: '2025-12-13',
    languages: ['English', 'Hindi'],
    aiScore: 7.8,
    age: 28,
    dateOfBirth: '1997-03-10',
    passportNumber: 'J1234567',
    passportExpiry: '2027-09-15',
    religion: 'Hindu',
    maritalStatus: 'Single',
    currentLocation: 'Mumbai, India',
    salaryExpectation: 'QAR 1,600',
    availableFrom: '2026-02-01',
    lastContacted: '2025-12-14',
    whatsappLink: 'https://wa.me/919876543210',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 0,
    englishLevel: 'Fluent',
    arabicLevel: 'None',
  },
  {
    id: '4',
    name: 'Suresh Patel',
    email: 'suresh.patel@email.com',
    phone: '+91 87654 32109',
    nationality: 'India',
    position: 'Plumber',
    country: 'UAE',
    experience: 6,
    status: 'Pending',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Pipe Installation', 'Drainage Systems', 'Water Systems', 'Maintenance'],
    appliedDate: '2025-12-11',
    languages: ['English', 'Hindi', 'Gujarati'],
    aiScore: 8.1,
    age: 29,
    dateOfBirth: '1996-07-18',
    passportNumber: 'K9876543',
    passportExpiry: '2028-12-05',
    religion: 'Hindu',
    maritalStatus: 'Married',
    currentLocation: 'Ahmedabad, India',
    salaryExpectation: 'AED 1,800',
    availableFrom: '2026-01-15',
    lastContacted: '2025-12-12',
    whatsappLink: 'https://wa.me/918765432109',
    videoLink: 'https://youtube.com/watch?v=plumber-demo-video',
    drivingLicense: 'None',
    yearsInGCC: 1,
    englishLevel: 'Intermediate',
    arabicLevel: 'None',
  },
  {
    id: '5',
    name: 'Kamal Uddin',
    email: 'kamal.uddin@email.com',
    phone: '+880 1712 345678',
    nationality: 'Bangladesh',
    position: 'Carpenter',
    country: 'Oman',
    experience: 8,
    status: 'Applied',
    source: 'Form',
    passportAvailable: false,
    skills: ['Woodwork', 'Furniture Making', 'Interior Finishing', 'Blueprint Reading'],
    appliedDate: '2025-12-12',
    languages: ['English', 'Bengali'],
    aiScore: 7.5,
    age: 34,
    dateOfBirth: '1991-02-20',
    currentLocation: 'Dhaka, Bangladesh',
    salaryExpectation: 'OMR 220',
    availableFrom: '2026-02-01',
    whatsappLink: 'https://wa.me/8801712345678',
    videoLink: 'https://youtube.com/watch?v=carpenter-skills-demo',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 0,
    englishLevel: 'Basic',
    arabicLevel: 'None',
  },
  {
    id: '6',
    name: 'Imran Sheikh',
    email: 'imran.sheikh@email.com',
    phone: '+92 302 3456789',
    nationality: 'Pakistan',
    position: 'Electrician',
    country: 'Saudi Arabia',
    experience: 3,
    status: 'Cancelled',
    source: 'Manual',
    passportAvailable: true,
    skills: ['Residential Wiring', 'Troubleshooting', 'Panel Installation'],
    appliedDate: '2025-12-08',
    languages: ['English', 'Urdu'],
    aiScore: 6.5,
    videoLink: 'https://youtube.com/watch?v=electrical-work-sample',
    whatsappLink: 'https://wa.me/923023456789',
  },
  {
    id: '7',
    name: 'Vijay Singh',
    email: 'vijay.singh@email.com',
    phone: '+91 99887 76655',
    nationality: 'India',
    position: 'Heavy Driver',
    country: 'UAE',
    experience: 10,
    status: 'Deployed',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Truck Driving', 'Heavy Equipment', 'UAE License', 'Logistics'],
    appliedDate: '2025-11-20',
    languages: ['English', 'Hindi', 'Punjabi'],
    aiScore: 9.0,
    age: 38,
    dateOfBirth: '1987-11-10',
    passportNumber: 'L5544332',
    passportExpiry: '2027-08-15',
    religion: 'Sikh',
    maritalStatus: 'Married',
    currentLocation: 'Dubai, UAE',
    salaryExpectation: 'AED 3,500',
    availableFrom: 'Currently Working',
    linkedinUrl: 'https://linkedin.com/in/vijay-singh-driver',
    whatsappLink: 'https://wa.me/919988776655',
    videoLink: 'https://youtube.com/watch?v=heavy-vehicle-driving',
    drivingLicense: 'Heavy Vehicle',
    yearsInGCC: 8,
    englishLevel: 'Fluent',
    arabicLevel: 'Intermediate',
  },
  {
    id: '8',
    name: 'Abdul Rahman',
    email: 'abdul.rahman@email.com',
    phone: '+92 303 4567890',
    nationality: 'Pakistan',
    position: 'Steel Fixer',
    country: 'Qatar',
    experience: 5,
    status: 'Pending',
    source: 'Email',
    passportAvailable: true,
    skills: ['Rebar Installation', 'Blueprint Reading', 'Construction', 'Safety'],
    appliedDate: '2025-12-09',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.3,
    age: 31,
    dateOfBirth: '1994-04-12',
    passportNumber: 'EF7788990',
    passportExpiry: '2029-01-25',
    religion: 'Muslim',
    maritalStatus: 'Single',
    currentLocation: 'Karachi, Pakistan',
    salaryExpectation: 'QAR 1,700',
    availableFrom: '2026-01-10',
    lastContacted: '2025-12-10',
    whatsappLink: 'https://wa.me/923034567890',
    videoLink: 'https://youtube.com/watch?v=steel-fixing-work',
    linkedinUrl: 'https://linkedin.com/in/abdul-rahman-steel',
    drivingLicense: 'None',
    yearsInGCC: 3,
    englishLevel: 'Intermediate',
    arabicLevel: 'Basic',
  },
  // More Electricians (mostly Pakistani)
  {
    id: '9',
    name: 'Usman Tariq',
    email: 'usman.tariq@email.com',
    phone: '+92 304 5678901',
    nationality: 'Pakistan',
    position: 'Electrician',
    country: 'UAE',
    experience: 4,
    status: 'Applied',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Electrical Installation', 'AC Systems', 'Building Wiring', 'Troubleshooting'],
    appliedDate: '2025-12-14',
    languages: ['English', 'Urdu'],
    aiScore: 7.9,
    age: 27,
    dateOfBirth: '1998-02-14',
    passportNumber: 'GH2345678',
    passportExpiry: '2028-11-10',
    medicalExpiry: '2026-03-15',
    religion: 'Muslim',
    maritalStatus: 'Single',
    currentLocation: 'Islamabad, Pakistan',
    salaryExpectation: 'AED 1,900',
    availableFrom: '2026-01-20',
    whatsappLink: 'https://wa.me/923045678901',
    videoLink: 'https://youtube.com/watch?v=electrician-usman',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 0,
    englishLevel: 'Intermediate',
    arabicLevel: 'None',
  },
  {
    id: '10',
    name: 'Shahid Mahmood',
    email: 'shahid.mahmood@email.com',
    phone: '+92 305 6789012',
    nationality: 'Pakistan',
    position: 'Electrician',
    country: 'Saudi Arabia',
    experience: 8,
    status: 'Pending',
    source: 'Email',
    passportAvailable: true,
    skills: ['Industrial Wiring', 'PLC Systems', 'Motor Control', 'High Voltage'],
    appliedDate: '2025-12-12',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.8,
    age: 36,
    dateOfBirth: '1989-06-20',
    passportNumber: 'IJ3456789',
    passportExpiry: '2029-04-15',
    medicalExpiry: '2026-08-20',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Faisalabad, Pakistan',
    salaryExpectation: 'SAR 2,200',
    availableFrom: '2026-01-05',
    lastContacted: '2025-12-13',
    whatsappLink: 'https://wa.me/923056789012',
    videoLink: 'https://youtube.com/watch?v=electrician-shahid',
    linkedinUrl: 'https://linkedin.com/in/shahid-mahmood-electrician',
    drivingLicense: 'None',
    yearsInGCC: 4,
    englishLevel: 'Fluent',
    arabicLevel: 'Intermediate',
  },
  {
    id: '11',
    name: 'Naveed Akhtar',
    email: 'naveed.akhtar@email.com',
    phone: '+92 306 7890123',
    nationality: 'Pakistan',
    position: 'Electrician',
    country: 'Serbia',
    experience: 6,
    status: 'Applied',
    source: 'Form',
    passportAvailable: true,
    skills: ['European Standards', 'Residential Wiring', 'Commercial Setup', 'Safety Compliance'],
    appliedDate: '2025-12-15',
    languages: ['English', 'Urdu'],
    aiScore: 8.2,
    age: 33,
    dateOfBirth: '1992-09-08',
    passportNumber: 'KL4567890',
    passportExpiry: '2028-07-25',
    medicalExpiry: '2026-12-10',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Rawalpindi, Pakistan',
    salaryExpectation: 'EUR 1,200',
    availableFrom: '2026-02-15',
    whatsappLink: 'https://wa.me/923067890123',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 0,
    englishLevel: 'Fluent',
    arabicLevel: 'None',
  },
  {
    id: '12',
    name: 'Zubair Hussain',
    email: 'zubair.hussain@email.com',
    phone: '+92 307 8901234',
    nationality: 'Pakistan',
    position: 'Electrician',
    country: 'UAE',
    experience: 5,
    status: 'Deployed',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Building Management Systems', 'Fire Alarm', 'CCTV Installation', 'Networking'],
    appliedDate: '2025-11-28',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.6,
    age: 30,
    dateOfBirth: '1995-04-17',
    passportNumber: 'MN5678901',
    passportExpiry: '2027-10-30',
    religion: 'Muslim',
    maritalStatus: 'Single',
    currentLocation: 'Abu Dhabi, UAE',
    salaryExpectation: 'AED 2,100',
    availableFrom: 'Currently Working',
    lastContacted: '2025-12-05',
    whatsappLink: 'https://wa.me/923078901234',
    videoLink: 'https://youtube.com/watch?v=electrician-zubair',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 3,
    englishLevel: 'Fluent',
    arabicLevel: 'Intermediate',
  },
  // More Drivers (mostly Pakistani)
  {
    id: '13',
    name: 'Waqas Ali',
    email: 'waqas.ali@email.com',
    phone: '+92 308 9012345',
    nationality: 'Pakistan',
    position: 'Light Driver',
    country: 'UAE',
    experience: 7,
    status: 'Applied',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Personal Driving', 'UAE License', 'Safe Driving', 'Navigation'],
    appliedDate: '2025-12-16',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.0,
    age: 34,
    dateOfBirth: '1991-07-22',
    passportNumber: 'OP6789012',
    passportExpiry: '2028-05-18',
    medicalExpiry: '2026-09-15',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Multan, Pakistan',
    salaryExpectation: 'AED 2,500',
    availableFrom: '2026-01-10',
    whatsappLink: 'https://wa.me/923089012345',
    videoLink: 'https://youtube.com/watch?v=driver-waqas',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 2,
    englishLevel: 'Intermediate',
    arabicLevel: 'Basic',
  },
  {
    id: '14',
    name: 'Fahad Malik',
    email: 'fahad.malik@email.com',
    phone: '+92 309 0123456',
    nationality: 'Pakistan',
    position: 'Heavy Driver',
    country: 'Saudi Arabia',
    experience: 9,
    status: 'Pending',
    source: 'Email',
    passportAvailable: true,
    skills: ['Truck Driving', 'Trailer Operation', 'Long Distance', 'Logistics'],
    appliedDate: '2025-12-11',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.9,
    age: 40,
    dateOfBirth: '1985-03-30',
    passportNumber: 'QR7890123',
    passportExpiry: '2029-02-20',
    medicalExpiry: '2026-06-25',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Sialkot, Pakistan',
    salaryExpectation: 'SAR 3,000',
    availableFrom: '2026-01-15',
    lastContacted: '2025-12-12',
    whatsappLink: 'https://wa.me/923090123456',
    videoLink: 'https://youtube.com/watch?v=heavy-driver-fahad',
    linkedinUrl: 'https://linkedin.com/in/fahad-malik-driver',
    drivingLicense: 'Heavy Vehicle',
    yearsInGCC: 6,
    englishLevel: 'Intermediate',
    arabicLevel: 'Fluent',
  },
  {
    id: '15',
    name: 'Bilal Ahmed',
    email: 'bilal.ahmed@email.com',
    phone: '+92 310 1234567',
    nationality: 'Pakistan',
    position: 'Light Driver',
    country: 'Kosovo',
    experience: 5,
    status: 'Applied',
    source: 'Form',
    passportAvailable: true,
    skills: ['European Driving', 'GPS Navigation', 'Customer Service', 'Safe Driving'],
    appliedDate: '2025-12-17',
    languages: ['English', 'Urdu'],
    aiScore: 7.6,
    age: 29,
    dateOfBirth: '1996-11-05',
    passportNumber: 'ST8901234',
    passportExpiry: '2028-08-12',
    medicalExpiry: '2026-10-18',
    religion: 'Muslim',
    maritalStatus: 'Single',
    currentLocation: 'Lahore, Pakistan',
    salaryExpectation: 'EUR 900',
    availableFrom: '2026-02-20',
    whatsappLink: 'https://wa.me/923101234567',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 0,
    englishLevel: 'Fluent',
    arabicLevel: 'None',
  },
  {
    id: '16',
    name: 'Asif Raza',
    email: 'asif.raza@email.com',
    phone: '+92 311 2345678',
    nationality: 'Pakistan',
    position: 'Heavy Driver',
    country: 'UAE',
    experience: 12,
    status: 'Deployed',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Dump Truck', 'Crane Operation', 'Heavy Equipment', 'Construction Sites'],
    appliedDate: '2025-11-22',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 9.1,
    age: 42,
    dateOfBirth: '1983-01-15',
    passportNumber: 'UV9012345',
    passportExpiry: '2027-12-08',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Sharjah, UAE',
    salaryExpectation: 'AED 4,000',
    availableFrom: 'Currently Working',
    lastContacted: '2025-12-08',
    whatsappLink: 'https://wa.me/923112345678',
    videoLink: 'https://youtube.com/watch?v=heavy-driver-asif',
    drivingLicense: 'Heavy Vehicle',
    yearsInGCC: 10,
    englishLevel: 'Intermediate',
    arabicLevel: 'Fluent',
  },
  // More Plumbers (mostly Pakistani)
  {
    id: '17',
    name: 'Kashif Mehmood',
    email: 'kashif.mehmood@email.com',
    phone: '+92 312 3456789',
    nationality: 'Pakistan',
    position: 'Plumber',
    country: 'UAE',
    experience: 6,
    status: 'Applied',
    source: 'Email',
    passportAvailable: true,
    skills: ['Pipe Installation', 'Sanitary Fitting', 'Water Heaters', 'Drainage'],
    appliedDate: '2025-12-14',
    languages: ['English', 'Urdu'],
    aiScore: 8.1,
    age: 31,
    dateOfBirth: '1994-08-25',
    passportNumber: 'WX0123456',
    passportExpiry: '2028-09-30',
    medicalExpiry: '2026-11-12',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Gujranwala, Pakistan',
    salaryExpectation: 'AED 1,850',
    availableFrom: '2026-01-25',
    whatsappLink: 'https://wa.me/923123456789',
    videoLink: 'https://youtube.com/watch?v=plumber-kashif',
    drivingLicense: 'None',
    yearsInGCC: 1,
    englishLevel: 'Intermediate',
    arabicLevel: 'Basic',
  },
  {
    id: '18',
    name: 'Hamza Qureshi',
    email: 'hamza.qureshi@email.com',
    phone: '+92 313 4567890',
    nationality: 'Pakistan',
    position: 'Plumber',
    country: 'Saudi Arabia',
    experience: 7,
    status: 'Pending',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Commercial Plumbing', 'HVAC Systems', 'Maintenance', 'Repair'],
    appliedDate: '2025-12-10',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.4,
    age: 35,
    dateOfBirth: '1990-05-12',
    passportNumber: 'YZ1234567',
    passportExpiry: '2029-03-18',
    medicalExpiry: '2026-07-20',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Peshawar, Pakistan',
    salaryExpectation: 'SAR 2,000',
    availableFrom: '2026-01-08',
    lastContacted: '2025-12-11',
    whatsappLink: 'https://wa.me/923134567890',
    videoLink: 'https://youtube.com/watch?v=plumber-hamza',
    linkedinUrl: 'https://linkedin.com/in/hamza-qureshi-plumber',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 3,
    englishLevel: 'Fluent',
    arabicLevel: 'Intermediate',
  },
  {
    id: '19',
    name: 'Tariq Aziz',
    email: 'tariq.aziz@email.com',
    phone: '+92 314 5678901',
    nationality: 'Pakistan',
    position: 'Plumber',
    country: 'Serbia',
    experience: 5,
    status: 'Applied',
    source: 'Form',
    passportAvailable: true,
    skills: ['European Standards', 'Residential Plumbing', 'Bathroom Fitting', 'Kitchen Setup'],
    appliedDate: '2025-12-18',
    languages: ['English', 'Urdu'],
    aiScore: 7.8,
    age: 28,
    dateOfBirth: '1997-10-03',
    passportNumber: 'AB2345678',
    passportExpiry: '2028-06-14',
    medicalExpiry: '2026-12-05',
    religion: 'Muslim',
    maritalStatus: 'Single',
    currentLocation: 'Karachi, Pakistan',
    salaryExpectation: 'EUR 1,100',
    availableFrom: '2026-02-28',
    whatsappLink: 'https://wa.me/923145678901',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 0,
    englishLevel: 'Fluent',
    arabicLevel: 'None',
  },
  {
    id: '20',
    name: 'Rizwan Shah',
    email: 'rizwan.shah@email.com',
    phone: '+92 315 6789012',
    nationality: 'Pakistan',
    position: 'Plumber',
    country: 'UAE',
    experience: 9,
    status: 'Deployed',
    source: 'Email',
    passportAvailable: true,
    skills: ['High-rise Buildings', 'Fire Fighting Systems', 'Water Supply', 'Pump Installation'],
    appliedDate: '2025-11-25',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.7,
    age: 38,
    dateOfBirth: '1987-02-28',
    passportNumber: 'CD3456789',
    passportExpiry: '2027-11-22',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Dubai, UAE',
    salaryExpectation: 'AED 2,200',
    availableFrom: 'Currently Working',
    lastContacted: '2025-12-02',
    whatsappLink: 'https://wa.me/923156789012',
    videoLink: 'https://youtube.com/watch?v=plumber-rizwan',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 7,
    englishLevel: 'Fluent',
    arabicLevel: 'Fluent',
  },
  // Beauticians (mostly Pakistani)
  {
    id: '21',
    name: 'Ayesha Malik',
    email: 'ayesha.malik@email.com',
    phone: '+92 316 7890123',
    nationality: 'Pakistan',
    position: 'Beautician',
    country: 'UAE',
    experience: 5,
    status: 'Applied',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Makeup Artist', 'Hair Styling', 'Bridal Makeup', 'Facial Treatments'],
    appliedDate: '2025-12-15',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.3,
    age: 27,
    dateOfBirth: '1998-06-12',
    passportNumber: 'EF4567890',
    passportExpiry: '2028-04-20',
    medicalExpiry: '2026-08-15',
    religion: 'Muslim',
    maritalStatus: 'Single',
    currentLocation: 'Lahore, Pakistan',
    salaryExpectation: 'AED 2,500',
    availableFrom: '2026-01-20',
    whatsappLink: 'https://wa.me/923167890123',
    videoLink: 'https://youtube.com/watch?v=beautician-ayesha',
    drivingLicense: 'None',
    yearsInGCC: 0,
    englishLevel: 'Fluent',
    arabicLevel: 'Basic',
  },
  {
    id: '22',
    name: 'Sana Tariq',
    email: 'sana.tariq@email.com',
    phone: '+92 317 8901234',
    nationality: 'Pakistan',
    position: 'Beautician',
    country: 'Saudi Arabia',
    experience: 6,
    status: 'Pending',
    source: 'Form',
    passportAvailable: true,
    skills: ['Nail Art', 'Spa Treatments', 'Waxing', 'Threading', 'Manicure & Pedicure'],
    appliedDate: '2025-12-12',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.5,
    age: 29,
    dateOfBirth: '1996-09-18',
    passportNumber: 'GH5678901',
    passportExpiry: '2028-12-10',
    medicalExpiry: '2026-10-22',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Islamabad, Pakistan',
    salaryExpectation: 'SAR 2,200',
    availableFrom: '2026-01-12',
    lastContacted: '2025-12-13',
    whatsappLink: 'https://wa.me/923178901234',
    videoLink: 'https://youtube.com/watch?v=beautician-sana',
    linkedinUrl: 'https://linkedin.com/in/sana-tariq-beautician',
    drivingLicense: 'None',
    yearsInGCC: 2,
    englishLevel: 'Fluent',
    arabicLevel: 'Intermediate',
  },
  {
    id: '23',
    name: 'Hina Khan',
    email: 'hina.khan@email.com',
    phone: '+92 318 9012345',
    nationality: 'Pakistan',
    position: 'Beautician',
    country: 'UAE',
    experience: 8,
    status: 'Deployed',
    source: 'Email',
    passportAvailable: true,
    skills: ['Permanent Makeup', 'Laser Treatments', 'Anti-aging', 'Skin Care'],
    appliedDate: '2025-11-18',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 9.0,
    age: 33,
    dateOfBirth: '1992-03-22',
    passportNumber: 'IJ6789012',
    passportExpiry: '2027-10-15',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Dubai, UAE',
    salaryExpectation: 'AED 3,500',
    availableFrom: 'Currently Working',
    lastContacted: '2025-12-05',
    whatsappLink: 'https://wa.me/923189012345',
    videoLink: 'https://youtube.com/watch?v=beautician-hina',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 5,
    englishLevel: 'Fluent',
    arabicLevel: 'Fluent',
  },
  {
    id: '24',
    name: 'Farah Naz',
    email: 'farah.naz@email.com',
    phone: '+92 319 0123456',
    nationality: 'Pakistan',
    position: 'Beautician',
    country: 'Kosovo',
    experience: 4,
    status: 'Applied',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Hair Coloring', 'Hair Extensions', 'European Styling', 'Makeup'],
    appliedDate: '2025-12-19',
    languages: ['English', 'Urdu'],
    aiScore: 7.7,
    age: 26,
    dateOfBirth: '1999-07-08',
    passportNumber: 'KL7890123',
    passportExpiry: '2028-05-28',
    medicalExpiry: '2026-09-10',
    religion: 'Muslim',
    maritalStatus: 'Single',
    currentLocation: 'Karachi, Pakistan',
    salaryExpectation: 'EUR 950',
    availableFrom: '2026-03-01',
    whatsappLink: 'https://wa.me/923190123456',
    drivingLicense: 'None',
    yearsInGCC: 0,
    englishLevel: 'Fluent',
    arabicLevel: 'None',
  },
  // More Electricians
  {
    id: '25',
    name: 'Imran Abbas',
    email: 'imran.abbas@email.com',
    phone: '+92 320 1234567',
    nationality: 'Pakistan',
    position: 'Electrician',
    country: 'UAE',
    experience: 7,
    status: 'Applied',
    source: 'Email',
    passportAvailable: true,
    skills: ['Solar Panel Installation', 'Renewable Energy', 'Electrical Design', 'Testing'],
    appliedDate: '2025-12-13',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.6,
    age: 34,
    dateOfBirth: '1991-12-02',
    passportNumber: 'MN8901234',
    passportExpiry: '2029-01-18',
    medicalExpiry: '2026-05-25',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Multan, Pakistan',
    salaryExpectation: 'AED 2,300',
    availableFrom: '2026-01-18',
    whatsappLink: 'https://wa.me/923201234567',
    videoLink: 'https://youtube.com/watch?v=electrician-imran',
    linkedinUrl: 'https://linkedin.com/in/imran-abbas-electrician',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 3,
    englishLevel: 'Fluent',
    arabicLevel: 'Intermediate',
  },
  {
    id: '26',
    name: 'Salman Rashid',
    email: 'salman.rashid@email.com',
    phone: '+92 321 2345678',
    nationality: 'Pakistan',
    position: 'Electrician',
    country: 'Germany',
    experience: 9,
    status: 'Pending',
    source: 'Form',
    passportAvailable: true,
    skills: ['German Standards', 'VDE Compliance', 'Automation', 'Industrial Control'],
    appliedDate: '2025-12-16',
    languages: ['English', 'Urdu', 'German (Basic)'],
    aiScore: 8.9,
    age: 37,
    dateOfBirth: '1988-04-15',
    passportNumber: 'OP9012345',
    passportExpiry: '2028-08-22',
    medicalExpiry: '2026-11-30',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Faisalabad, Pakistan',
    salaryExpectation: 'EUR 2,200',
    availableFrom: '2026-03-15',
    whatsappLink: 'https://wa.me/923212345678',
    videoLink: 'https://youtube.com/watch?v=electrician-salman',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 0,
    englishLevel: 'Fluent',
    arabicLevel: 'None',
  },
  // More Drivers
  {
    id: '27',
    name: 'Yasir Mehmood',
    email: 'yasir.mehmood@email.com',
    phone: '+92 322 3456789',
    nationality: 'Pakistan',
    position: 'Light Driver',
    country: 'Saudi Arabia',
    experience: 6,
    status: 'Applied',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Family Driver', 'Airport Pickup', 'Safe Driving', 'Vehicle Maintenance'],
    appliedDate: '2025-12-17',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.0,
    age: 32,
    dateOfBirth: '1993-08-10',
    passportNumber: 'QR0123456',
    passportExpiry: '2028-07-05',
    medicalExpiry: '2026-10-12',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Sialkot, Pakistan',
    salaryExpectation: 'SAR 2,400',
    availableFrom: '2026-01-22',
    whatsappLink: 'https://wa.me/923223456789',
    videoLink: 'https://youtube.com/watch?v=driver-yasir',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 2,
    englishLevel: 'Intermediate',
    arabicLevel: 'Intermediate',
  },
  {
    id: '28',
    name: 'Nadeem Ali',
    email: 'nadeem.ali@email.com',
    phone: '+92 323 4567890',
    nationality: 'Pakistan',
    position: 'Heavy Driver',
    country: 'UAE',
    experience: 11,
    status: 'Deployed',
    source: 'Email',
    passportAvailable: true,
    skills: ['Trailer Truck', 'Container Transport', 'Port Operations', 'Long Haul'],
    appliedDate: '2025-11-20',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 9.2,
    age: 43,
    dateOfBirth: '1982-06-18',
    passportNumber: 'ST1234567',
    passportExpiry: '2027-09-12',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Jebel Ali, UAE',
    salaryExpectation: 'AED 4,500',
    availableFrom: 'Currently Working',
    lastContacted: '2025-12-10',
    whatsappLink: 'https://wa.me/923234567890',
    videoLink: 'https://youtube.com/watch?v=heavy-driver-nadeem',
    drivingLicense: 'Heavy Vehicle',
    yearsInGCC: 9,
    englishLevel: 'Intermediate',
    arabicLevel: 'Fluent',
  },
  // More Plumbers
  {
    id: '29',
    name: 'Aamir Siddique',
    email: 'aamir.siddique@email.com',
    phone: '+92 324 5678901',
    nationality: 'Pakistan',
    position: 'Plumber',
    country: 'UAE',
    experience: 8,
    status: 'Applied',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Villa Plumbing', 'Swimming Pool Systems', 'Jacuzzi Installation', 'Luxury Homes'],
    appliedDate: '2025-12-14',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.5,
    age: 36,
    dateOfBirth: '1989-11-28',
    passportNumber: 'UV2345678',
    passportExpiry: '2029-02-14',
    medicalExpiry: '2026-06-18',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Rawalpindi, Pakistan',
    salaryExpectation: 'AED 2,100',
    availableFrom: '2026-01-28',
    whatsappLink: 'https://wa.me/923245678901',
    videoLink: 'https://youtube.com/watch?v=plumber-aamir',
    linkedinUrl: 'https://linkedin.com/in/aamir-siddique-plumber',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 4,
    englishLevel: 'Fluent',
    arabicLevel: 'Intermediate',
  },
  {
    id: '30',
    name: 'Faisal Khan',
    email: 'faisal.khan@email.com',
    phone: '+92 325 6789012',
    nationality: 'Pakistan',
    position: 'Plumber',
    country: 'Austria',
    experience: 6,
    status: 'Applied',
    source: 'Form',
    passportAvailable: true,
    skills: ['European Standards', 'Heating Systems', 'Radiator Installation', 'Gas Fitting'],
    appliedDate: '2025-12-18',
    languages: ['English', 'Urdu'],
    aiScore: 8.2,
    age: 33,
    dateOfBirth: '1992-01-20',
    passportNumber: 'WX3456789',
    passportExpiry: '2028-10-08',
    medicalExpiry: '2026-12-20',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Gujranwala, Pakistan',
    salaryExpectation: 'EUR 1,800',
    availableFrom: '2026-03-10',
    whatsappLink: 'https://wa.me/923256789012',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 0,
    englishLevel: 'Fluent',
    arabicLevel: 'None',
  },
  // More Beauticians
  {
    id: '31',
    name: 'Zainab Riaz',
    email: 'zainab.riaz@email.com',
    phone: '+92 326 7890123',
    nationality: 'Pakistan',
    position: 'Beautician',
    country: 'UAE',
    experience: 7,
    status: 'Pending',
    source: 'Email',
    passportAvailable: true,
    skills: ['Microblading', 'Eyelash Extensions', 'Henna Art', 'Makeup Training'],
    appliedDate: '2025-12-11',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.7,
    age: 31,
    dateOfBirth: '1994-05-16',
    passportNumber: 'YZ4567890',
    passportExpiry: '2028-11-25',
    medicalExpiry: '2026-08-08',
    religion: 'Muslim',
    maritalStatus: 'Married',
    currentLocation: 'Peshawar, Pakistan',
    salaryExpectation: 'AED 3,000',
    availableFrom: '2026-01-15',
    lastContacted: '2025-12-12',
    whatsappLink: 'https://wa.me/923267890123',
    videoLink: 'https://youtube.com/watch?v=beautician-zainab',
    drivingLicense: 'Light Vehicle',
    yearsInGCC: 3,
    englishLevel: 'Fluent',
    arabicLevel: 'Intermediate',
  },
  {
    id: '32',
    name: 'Mehwish Ahmed',
    email: 'mehwish.ahmed@email.com',
    phone: '+92 327 8901234',
    nationality: 'Pakistan',
    position: 'Beautician',
    country: 'Saudi Arabia',
    experience: 5,
    status: 'Applied',
    source: 'WhatsApp',
    passportAvailable: true,
    skills: ['Hijab Styling', 'Arabic Makeup', 'Traditional Henna', 'Party Makeup'],
    appliedDate: '2025-12-16',
    languages: ['English', 'Urdu', 'Arabic'],
    aiScore: 8.1,
    age: 28,
    dateOfBirth: '1997-09-03',
    passportNumber: 'AB5678901',
    passportExpiry: '2028-06-30',
    medicalExpiry: '2026-09-22',
    religion: 'Muslim',
    maritalStatus: 'Single',
    currentLocation: 'Lahore, Pakistan',
    salaryExpectation: 'SAR 2,500',
    availableFrom: '2026-02-05',
    whatsappLink: 'https://wa.me/923278901234',
    videoLink: 'https://youtube.com/watch?v=beautician-mehwish',
    drivingLicense: 'None',
    yearsInGCC: 1,
    englishLevel: 'Fluent',
    arabicLevel: 'Intermediate',
  },
];

export const mockEmployers: Employer[] = [
  {
    id: '1',
    companyName: 'Al Majid Construction LLC',
    country: 'UAE',
    contactPerson: 'Hassan Al Majid',
    email: 'hr@almajid.ae',
    phone: '+971 4 123 4567',
    categories: ['Electrician', 'Plumber', 'Mason', 'Carpenter'],
    activeJobs: 3,
  },
  {
    id: '2',
    companyName: 'Saudi Build Group',
    country: 'Saudi Arabia',
    contactPerson: 'Abdullah bin Salman',
    email: 'recruitment@saudibuild.sa',
    phone: '+966 11 234 5678',
    categories: ['Welder', 'Electrician', 'Steel Fixer'],
    activeJobs: 2,
  },
  {
    id: '3',
    companyName: 'Qatar Development Co.',
    country: 'Qatar',
    contactPerson: 'Mohammed Al Thani',
    email: 'jobs@qatardev.qa',
    phone: '+974 4444 5555',
    categories: ['Mason', 'Carpenter', 'Heavy Driver'],
    activeJobs: 4,
  },
  {
    id: '4',
    companyName: 'Oman Infrastructure',
    country: 'Oman',
    contactPerson: 'Said Al Balushi',
    email: 'hr@omaninfra.om',
    phone: '+968 2456 7890',
    categories: ['Electrician', 'Plumber', 'Carpenter'],
    activeJobs: 1,
  },
];

export const mockJobOrders: JobOrder[] = [
  {
    id: '1',
    employerId: '1',
    employerName: 'Al Majid Construction LLC',
    position: 'Electrician',
    country: 'UAE',
    salary: 'AED 1,800 - 2,200',
    candidates: 5,
    urgency: 'High',
    skills: ['Electrical Installation', 'Industrial Wiring', 'Safety Standards', 'Maintenance'],
    status: 'Open',
    createdDate: '2025-12-01',
  },
  {
    id: '2',
    employerId: '2',
    employerName: 'Saudi Build Group',
    position: 'Welder',
    country: 'Saudi Arabia',
    salary: 'SAR 2,000 - 2,500',
    candidates: 10,
    urgency: 'High',
    skills: ['TIG Welding', 'MIG Welding', 'Arc Welding', 'Metal Fabrication'],
    status: 'Open',
    createdDate: '2025-11-28',
  },
  {
    id: '3',
    employerId: '1',
    employerName: 'Al Majid Construction LLC',
    position: 'Plumber',
    country: 'UAE',
    salary: 'AED 1,600 - 2,000',
    candidates: 3,
    urgency: 'Medium',
    skills: ['Pipe Installation', 'Water Systems', 'Drainage Systems', 'Maintenance'],
    status: 'Open',
    createdDate: '2025-12-05',
  },
  {
    id: '4',
    employerId: '3',
    employerName: 'Qatar Development Co.',
    position: 'Mason',
    country: 'Qatar',
    salary: 'QAR 1,500 - 1,800',
    candidates: 8,
    urgency: 'Low',
    skills: ['Bricklaying', 'Plastering', 'Tiling', 'Construction'],
    status: 'Open',
    createdDate: '2025-11-25',
  },
  {
    id: '5',
    employerId: '4',
    employerName: 'Oman Infrastructure',
    position: 'Carpenter',
    country: 'Oman',
    salary: 'OMR 200 - 250',
    candidates: 2,
    urgency: 'Medium',
    skills: ['Woodwork', 'Furniture Making', 'Interior Finishing', 'Blueprint Reading'],
    status: 'Open',
    createdDate: '2025-12-07',
  },
  {
    id: '6',
    employerId: '3',
    employerName: 'Qatar Development Co.',
    position: 'Heavy Driver',
    country: 'Qatar',
    salary: 'QAR 2,200 - 2,800',
    candidates: 15,
    urgency: 'High',
    skills: ['Truck Driving', 'Heavy Equipment', 'Valid License', 'Logistics'],
    status: 'Closed',
    createdDate: '2025-11-10',
  },
];