-- 004_enable_rls.sql

-- Enable RLS on tables (example list)
ALTER TABLE IF EXISTS candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS candidate_timeline ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS employers ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS job_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS inbox_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS inbox_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS parsing_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS communication_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS communication_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS job_candidate_matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS matching_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS cv_versions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS share_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS form_submissions ENABLE ROW LEVEL SECURITY;
