-- Review templates table — 200 pre-written short review texts
CREATE TABLE IF NOT EXISTS review_templates (
  id      smallint PRIMARY KEY,
  text    text NOT NULL
);

INSERT INTO review_templates (id, text) VALUES
(1,  'Best manpower agency in Islamabad.'),
(2,  'Excellent overseas employment service.'),
(3,  'Very professional recruitment agency.'),
(4,  'I got job through FALISHA manpower.'),
(5,  'Highly recommended consultancy.'),
(6,  'Good overseas job guidance.'),
(7,  'Trusted manpower agency in Pakistan.'),
(8,  'Helpful staff and good service.'),
(9,  'I am satisfied with their process.'),
(10, 'Best recruitment agency for Gulf jobs.'),
(11, 'I got Saudi Arabia job through them.'),
(12, 'Good manpower recruitment service.'),
(13, 'Excellent visa processing help.'),
(14, 'Professional overseas employment agency.'),
(15, 'Fast response and good support.'),
(16, 'Trusted overseas job consultant.'),
(17, 'Good data bank of candidates.'),
(18, 'Recommended manpower agency.'),
(19, 'Honest and reliable service.'),
(20, 'Good consultancy in Islamabad.'),
(21, 'I am working in UAE through them.'),
(22, 'Best agency for Qatar jobs.'),
(23, 'Good Bahrain employment service.'),
(24, 'Excellent Saudi recruitment support.'),
(25, 'I got job visa through FALISHA manpower.'),
(26, 'Good Gulf job consultancy.'),
(27, 'Professional recruitment team.'),
(28, 'Highly satisfied with service.'),
(29, 'Best manpower exporter from Pakistan.'),
(30, 'Good technical worker placement.'),
(31, 'I got electrician job abroad.'),
(32, 'Good welding job recruitment.'),
(33, 'Best HVAC technician placement.'),
(34, 'Excellent mechanical worker job.'),
(35, 'I am working in Saudi project.'),
(36, 'Good construction job consultancy.'),
(37, 'Trusted manpower recruitment.'),
(38, 'Fast processing agency.'),
(39, 'Professional overseas recruitment.'),
(40, 'Good overseas career help.'),
(41, 'I got labor job in Bahrain.'),
(42, 'Best manpower agency in Islamabad.'),
(43, 'Excellent job placement service.'),
(44, 'Good overseas employment support.'),
(45, 'Trusted recruitment firm.'),
(46, 'Helpful recruitment staff.'),
(47, 'Good communication service.'),
(48, 'I am satisfied with FALISHA manpower.'),
(49, 'Recommended agency for foreign jobs.'),
(50, 'Professional manpower consultancy.'),
(51, 'Good Gulf employment agency.'),
(52, 'Best recruitment service in Pakistan.'),
(53, 'Excellent manpower supply.'),
(54, 'Trusted overseas job agency.'),
(55, 'I got foreign employment opportunity.'),
(56, 'Good visa assistance service.'),
(57, 'Professional recruitment process.'),
(58, 'Highly recommended manpower agency.'),
(59, 'Best manpower consultant in Islamabad.'),
(60, 'Good overseas placement agency.'),
(61, 'I got job in Saudi Arabia.'),
(62, 'Excellent recruitment service.'),
(63, 'Good manpower support.'),
(64, 'Trusted overseas consultancy.'),
(65, 'Professional staff behavior.'),
(66, 'Fast visa guidance.'),
(67, 'Good job opportunity abroad.'),
(68, 'I am satisfied with their service.'),
(69, 'Best manpower recruitment.'),
(70, 'Excellent HR service.'),
(71, 'Good recruitment partner.'),
(72, 'Trusted manpower exporter.'),
(73, 'Best overseas employment service.'),
(74, 'Professional manpower team.'),
(75, 'Good technical job placement.'),
(76, 'Excellent visa processing.'),
(77, 'Highly satisfied client.'),
(78, 'Recommended consultancy.'),
(79, 'Good manpower service.'),
(80, 'Best recruitment agency.'),
(81, 'I got job visa for Turkey.'),
(82, 'Good Russia job consultancy.'),
(83, 'Best Belarus employment agency.'),
(84, 'Excellent Malaysia job service.'),
(85, 'Trusted overseas recruitment.'),
(86, 'Good foreign employment help.'),
(87, 'Professional recruitment support.'),
(88, 'Best manpower data bank.'),
(89, 'Highly recommended agency.'),
(90, 'Excellent job placement.'),
(91, 'Good Gulf manpower recruitment.'),
(92, 'Best agency for Saudi workers.'),
(93, 'Excellent overseas career service.'),
(94, 'Trusted manpower consultancy.'),
(95, 'Good HR recruitment service.'),
(96, 'Professional overseas agency.'),
(97, 'Best manpower provider.'),
(98, 'Excellent recruitment company.'),
(99, 'Highly satisfied service.'),
(100,'Good job processing support.'),
(101,'Best manpower recruitment in Islamabad.'),
(102,'Excellent overseas employment help.'),
(103,'Professional manpower exporter.'),
(104,'Good placement service.'),
(105,'Trusted agency for Gulf jobs.'),
(106,'Best overseas job consultancy.'),
(107,'Excellent recruitment management.'),
(108,'Good worker placement service.'),
(109,'Highly recommended consultancy.'),
(110,'Professional recruitment firm.'),
(111,'Good manpower supply agency.'),
(112,'Best for skilled workers.'),
(113,'Excellent technical recruitment.'),
(114,'Trusted overseas job service.'),
(115,'Good visa processing help.'),
(116,'Professional staff.'),
(117,'Best recruitment partner.'),
(118,'Excellent manpower export.'),
(119,'Highly satisfied client.'),
(120,'Good overseas employment.'),
(121,'I am working abroad through them.'),
(122,'Best Gulf job agency.'),
(123,'Good recruitment experience.'),
(124,'Trusted consultancy.'),
(125,'Excellent manpower service.'),
(126,'Professional recruitment help.'),
(127,'Best manpower agency Pakistan.'),
(128,'Good overseas job support.'),
(129,'Highly recommended.'),
(130,'Excellent recruitment service.'),
(131,'Good job opportunity abroad.'),
(132,'Best manpower consultant.'),
(133,'Trusted recruitment agency.'),
(134,'Professional overseas service.'),
(135,'Good visa guidance.'),
(136,'Excellent placement agency.'),
(137,'Highly satisfied experience.'),
(138,'Best manpower exporter.'),
(139,'Good recruitment team.'),
(140,'Trusted manpower partner.'),
(141,'Excellent HR recruitment.'),
(142,'Good Gulf employment service.'),
(143,'Best manpower agency Islamabad.'),
(144,'Professional consultancy service.'),
(145,'Good overseas placement.'),
(146,'Trusted recruitment firm.'),
(147,'Excellent manpower support.'),
(148,'Highly recommended agency.'),
(149,'Good recruitment help.'),
(150,'Best manpower consultant Pakistan.'),
(151,'Excellent overseas job agency.'),
(152,'Good manpower recruitment.'),
(153,'Professional staff support.'),
(154,'Trusted overseas employment.'),
(155,'Best recruitment service.'),
(156,'Good visa processing.'),
(157,'Excellent manpower exporter.'),
(158,'Highly satisfied service.'),
(159,'Recommended manpower agency.'),
(160,'Good overseas consultancy.'),
(161,'Best manpower recruitment service.'),
(162,'Excellent job placement agency.'),
(163,'Professional HR service.'),
(164,'Trusted manpower consultancy.'),
(165,'Good recruitment partner.'),
(166,'Best overseas employment agency.'),
(167,'Excellent manpower supply.'),
(168,'Highly recommended service.'),
(169,'Good Gulf recruitment.'),
(170,'Trusted recruitment support.'),
(171,'Best manpower exporter Pakistan.'),
(172,'Excellent recruitment firm.'),
(173,'Good overseas job consultant.'),
(174,'Professional manpower service.'),
(175,'Trusted agency.'),
(176,'Best manpower consultancy.'),
(177,'Excellent job help.'),
(178,'Good recruitment experience.'),
(179,'Highly satisfied client.'),
(180,'Recommended agency.'),
(181,'Excellent manpower agency.'),
(182,'Good overseas employment.'),
(183,'Professional recruitment team.'),
(184,'Trusted manpower partner.'),
(185,'Best job placement agency.'),
(186,'Excellent visa help.'),
(187,'Good recruitment support.'),
(188,'Highly professional service.'),
(189,'Best manpower consultant.'),
(190,'Trusted overseas agency.'),
(191,'Excellent manpower recruitment.'),
(192,'Good job consultancy.'),
(193,'Professional HR recruitment.'),
(194,'Best overseas employment service.'),
(195,'Highly satisfied.'),
(196,'Good manpower supply.'),
(197,'Excellent recruitment help.'),
(198,'Trusted recruitment agency.'),
(199,'Best manpower agency Pakistan.'),
(200,'Highly recommended recruitment service.')
ON CONFLICT (id) DO UPDATE SET text = EXCLUDED.text;

-- No RLS needed — read-only public data
